cjstmdgusqw/Seoul_Transportation_vulnerable

- SeoulGuide/.classpath
- SeoulGuide/src/main/java/com/seoul/guide/member/Controller/MemberController.java
- SeoulGuide/src/main/java/com/seoul/guide/member/DAO/MemberDAO.java
- SeoulGuide/src/main/java/com/seoul/guide/member/DAO/MemberDAOImpl.java
- SeoulGuide/src/main/java/com/seoul/guide/member/DTO/FileVO.java
- SeoulGuide/src/main/java/com/seoul/guide/member/Service/MemberService.java
- SeoulGuide/src/main/java/com/seoul/guide/member/Service/MemberServiceImpl.java
- SeoulGuide/src/main/resources/sql/file.xml
- SeoulGuide/src/main/resources/sql/member.xml
- SeoulGuide/src/main/webapp/WEB-INF/views/boardWrite.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/main.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/member/login.jsp
- SeoulGuide/src/main/webapp/resources/css/header.css
login 기능 구현 완료 이메일로 입력을 하면 
email정보를 session에 담게하여 새롭게 넣어주었음
메인으로 이동하게했음
앞으로추가할 기능이 있다면 오류났을때 각각 페이지를 생성해야할것
> FEAT : 로그인 기능 구현

- SeoulGuide/pom.xml
- SeoulGuide/src/main/java/com/seoul/guide/member/Controller/MemberController.java
- SeoulGuide/src/main/java/com/seoul/guide/member/DTO/FileVO.java
- SeoulGuide/src/main/java/com/seoul/guide/member/DTO/MemberDTO.java
- SeoulGuide/src/main/resources/config/context-jdbc.xml
- SeoulGuide/src/main/resources/sql/member.xml
- SeoulGuide/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
- SeoulGuide/src/main/webapp/WEB-INF/spring/root-context.xml
- SeoulGuide/src/main/webapp/WEB-INF/views/member/join.jsp
- SeoulGuide/src/main/webapp/resources/css/member/join.css
- SeoulGuide/src/main/webapp/resources/js/join.js
1. 닉네임 중복체크 확인
2. 비밀번호 일치하는지여부 and 자릿수 여부 확인
3. 이메일 인증
> FEAT : join.jsp 회원가입 관련 중복체크 기능and 이메일기능 추가

- SeoulGuide/src/main/webapp/WEB-INF/views/member/join.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/tour/tour.jsp
- SeoulGuide/src/main/webapp/resources/js/join.js
비밀번호에  문자를쳐도 완료가 되는현상 수정(완료)
생년월일에 문자열을 쳐도 형식에 맞다고 완료가 뜨는 현상 수정 (완료)
> fix : join.jsp 비밀번호 and 생년월일 각종 버그 수정

- SeoulGuide/src/main/java/com/seoul/guide/member/DAO/MemberDAOImpl.java
- SeoulGuide/src/main/java/com/seoul/guide/member/Service/MemberServiceImpl.java
- SeoulGuide/src/main/resources/sql/file.xml
- SeoulGuide/src/main/webapp/WEB-INF/views/main.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/member/join.jsp
- SeoulGuide/src/main/webapp/resources/css/member/join.css
- SeoulGuide/src/main/webapp/resources/js/join.js
fix: join.jsp 회원가입 프로필 사진 업로드 기능 완성
> fix: join.jsp 회원가입 프로필 사진 업로드 기능 완성

- SeoulGuide/src/main/java/com/seoul/guide/board/Controller/BoardController.java
- SeoulGuide/src/main/java/com/seoul/guide/board/DAO/BoardDAO.java
- SeoulGuide/src/main/java/com/seoul/guide/board/DAO/BoardDAOImpl.java
- SeoulGuide/src/main/java/com/seoul/guide/board/Service/BoardService.java
- SeoulGuide/src/main/java/com/seoul/guide/board/Service/BoardServiceImpl.java
- SeoulGuide/src/main/resources/sql/board.xml
- SeoulGuide/src/main/webapp/WEB-INF/views/story/storyDetail.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/story/storyReview.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/story/writeform.jsp
- SeoulGuide/src/main/webapp/resources/css/story/storyReview.css
- SeoulGuide/src/main/webapp/resources/js/boardWrite.js
FEAT: TOAST API 데이터 업로드 및 , storyDetail.jsp에  API viewer 추가 
STYLE: storyReview.jsp , storyDetail.jsp의 storyReview.css 수정
> FEAT: TOAST API 기능 추가 , STYLE: storyReview.css 추가 및 수정

- .gitignore
- SeoulGuide/pom.xml
- SeoulGuide/src/main/java/com/seoul/guide/density/Controller/DensityController.java
- SeoulGuide/src/main/java/com/seoul/guide/density/Controller/DensityDetailController.java
- SeoulGuide/src/main/java/com/seoul/guide/density/DAO/DensityDAO.java
- SeoulGuide/src/main/java/com/seoul/guide/density/DAO/DensityDAOImpl.java
- SeoulGuide/src/main/java/com/seoul/guide/density/DTO/CityData.java
- SeoulGuide/src/main/java/com/seoul/guide/density/DTO/CityDataResponse.java
- SeoulGuide/src/main/java/com/seoul/guide/density/DTO/DensityDTO.java
- SeoulGuide/src/main/java/com/seoul/guide/density/DTO/InnerLivePopulationStatus.java
- SeoulGuide/src/main/java/com/seoul/guide/density/DTO/OuterLivePopulationStatus.java
- SeoulGuide/src/main/java/com/seoul/guide/density/Service/DensityService.java
- SeoulGuide/src/main/java/com/seoul/guide/density/Service/DensityServiceImpl.java
- SeoulGuide/src/main/resources/sql/density.xml
- SeoulGuide/src/main/webapp/WEB-INF/views/density/density.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/density/densityDetail.jsp
density.jsp, densityDetail.jsp - 인구밀집페이지와 인구밀집 및 교통정보 상세페이지 개발
density.xml - sql 쿼리문 작성
densityController, densityDetailController
densityDAO, densityDAOImpl
densityDTO, CityDataResponse, CityData, OuterLivePopulationStatus, InnerLivePopulationStatus - 서울시 API 데이터 파싱 및 데이터 전처리 개발
density.Service, serviceImpl
> FEAT : density.jsp - 인구밀집관련 정보 DB 정보 출력

- SeoulGuide/src/main/java/com/seoul/guide/tour/Controller/TourController.java
- SeoulGuide/src/main/java/com/seoul/guide/tour/DAO/TourDAO.java
- SeoulGuide/src/main/java/com/seoul/guide/tour/DAO/TourDAOImpl.java
- SeoulGuide/src/main/java/com/seoul/guide/tour/Service/TourService.java
- SeoulGuide/src/main/java/com/seoul/guide/tour/Service/TourServiceImpl.java
- SeoulGuide/src/main/resources/sql/tour.xml
- SeoulGuide/src/main/webapp/WEB-INF/spring/root-context.xml
- SeoulGuide/src/main/webapp/WEB-INF/views/tour/tour.jsp
- SeoulGuide/src/main/webapp/resources/css/tour/tour.css
tourController, tourDAO, tourDTO, tourService, tour.xml
상세 검색기능 구현 완료
1. 버튼클릭만으로 검색 가능
2. 지역만을 가지고 검색기능완료
3. 위에 두기능 합쳐서 검색하는 기능도 구현완료
> FEAT : tour.jsp 상세 검색기능 구현 완료

- SeoulGuide/src/main/java/com/seoul/guide/tour/Controller/TourController.java
- SeoulGuide/src/main/java/com/seoul/guide/tour/DAO/TourDAO.java
- SeoulGuide/src/main/java/com/seoul/guide/tour/DAO/TourDAOImpl.java
- SeoulGuide/src/main/java/com/seoul/guide/tour/Service/TourService.java
- SeoulGuide/src/main/java/com/seoul/guide/tour/Service/TourServiceImpl.java
- SeoulGuide/src/main/resources/sql/member.xml
- SeoulGuide/src/main/resources/sql/tour.xml
- SeoulGuide/src/main/webapp/WEB-INF/views/header.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/main.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/member/login.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/tour/tour.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/tour/tourdetail.jsp
- SeoulGuide/src/main/webapp/resources/css/member/login.css
- SeoulGuide/src/main/webapp/resources/css/tour/tour.css
- SeoulGuide/src/main/webapp/resources/css/tour/tourdetail.css
1. 상세페이지 이동 완료
2. 지도 자동 위치지정 완료
3. 댓글 진행중(진행중)
> FEAT : tourdetail.jsp 여행 상세내용 페이지 완성(댓글 진행중)

- SeoulGuide/src/main/java/com/seoul/guide/tour/Controller/TourController.java
- SeoulGuide/src/main/java/com/seoul/guide/tour/Service/TourServiceImpl.java
- SeoulGuide/src/main/resources/sql/tour.xml
- SeoulGuide/src/main/webapp/WEB-INF/views/tour/tourdetail.jsp
- SeoulGuide/src/main/webapp/resources/css/tour/tour.css
- SeoulGuide/src/main/webapp/resources/css/tour/tourdetail.css
> Fix : tour.jsp 사이즈 폭 수정완료

- SeoulGuide/src/main/java/com/seoul/guide/comment/Controller/CommentController.java
- SeoulGuide/src/main/java/com/seoul/guide/comment/DAO/CommentDAO.java
- SeoulGuide/src/main/java/com/seoul/guide/comment/DAO/CommentDAOImpl.java
- SeoulGuide/src/main/java/com/seoul/guide/comment/DTO/CommentDTO.java
- SeoulGuide/src/main/java/com/seoul/guide/comment/Service/CommentService.java
- SeoulGuide/src/main/java/com/seoul/guide/comment/Service/CommentServiceImpl.java
- SeoulGuide/src/main/java/com/seoul/guide/member/DTO/MemberDTO.java
- SeoulGuide/src/main/java/com/seoul/guide/member/Service/MemberServiceImpl.java
- SeoulGuide/src/main/java/com/seoul/guide/tour/Controller/TourController.java
- SeoulGuide/src/main/java/com/seoul/guide/tour/Service/TourServiceImpl.java
- SeoulGuide/src/main/resources/sql/comment.xml
- SeoulGuide/src/main/resources/sql/member.xml
- SeoulGuide/src/main/webapp/WEB-INF/views/tour/tourdetail.jsp
- SeoulGuide/src/main/webapp/resources/css/tour/tourdetail.css
- SeoulGuide/src/main/webapp/resources/js/boardWrite.js
- SeoulGuide/src/main/webapp/resources/js/comment.js
댓글 insert완료
댓글 조회 완료(프로필 사진 , 닉네임은 진행중)
> FEAT : detail.jsp (Comment) 댓글기능 추가 (진행중)

- SeoulGuide/src/main/webapp/WEB-INF/views/density/density.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/density/densityDetail.jsp
- density.jsp, densityDetail.jsp header, footer 추가 
- 프로젝트 표준 디자인코드 적용
> feat density.jsp, densityDetail.jsp header, footer 추가

- SeoulGuide/src/main/java/com/seoul/guide/density/Controller/DensityController.java
- SeoulGuide/src/main/java/com/seoul/guide/density/DAO/DensityDAO.java
- SeoulGuide/src/main/java/com/seoul/guide/density/DAO/DensityDAOImpl.java
- SeoulGuide/src/main/java/com/seoul/guide/density/Service/DensityService.java
- SeoulGuide/src/main/java/com/seoul/guide/density/Service/DensityServiceImpl.java
- SeoulGuide/src/main/resources/sql/density.xml
- SeoulGuide/src/main/webapp/WEB-INF/views/density/density.jsp
1. density페이지 PC화면에서 1줄로 나오던 오류 해결
2. density페이지 페이지네이션 개발
3. 페이지네이션에 맞게 VIEW단도 개발(JSP)
> feat density 페이지네이션, CSS수정

- SeoulGuide/src/main/java/com/seoul/guide/board/Controller/BoardController.java
- SeoulGuide/src/main/java/com/seoul/guide/board/DAO/BoardDAO.java
- SeoulGuide/src/main/java/com/seoul/guide/board/DAO/BoardDAOImpl.java
- SeoulGuide/src/main/java/com/seoul/guide/board/DTO/Article.java
- SeoulGuide/src/main/java/com/seoul/guide/board/Service/BoardService.java
- SeoulGuide/src/main/java/com/seoul/guide/board/Service/BoardServiceImpl.java
- SeoulGuide/src/main/resources/sql/board.xml
storydetail 들어갈때 마다 DB에서 조회수 +1씩되게
SQL문이랑 controller에서 코드 추가
> feat storydetail 조회수증가로직 추가

- SeoulGuide/pom.xml
- SeoulGuide/src/main/java/com/seoul/guide/board/Controller/BoardController.java
- SeoulGuide/src/main/webapp/WEB-INF/views/story/storyDetail.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/story/storyReview.jsp
- SeoulGuide/src/main/webapp/resources/css/story/storyReview.css
DOCS: BoardController.java, storyDetail.jsp  삭제 및 수정 버튼 게시글 작성자에게만 보이도록 수정, 삭제기능 추가
STYLE: storyDetail.jsp / storyRevuew.css 댓글 화면 추가 및 수정 및 삭제버튼 디자인 수정
> DOCS: BoardController.java, storyDetail.jsp 수정 STYLE: storyRevuew.css수정

- SeoulGuide/pom.xml
- SeoulGuide/src/main/java/com/seoul/guide/member/DAO/MemberDAO.java
- SeoulGuide/src/main/webapp/WEB-INF/views/myPage/profile.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/story/storyReview.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/tour/tour.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/tour/tourdetail.jsp
- SeoulGuide/src/main/webapp/resources/css/common.css
- SeoulGuide/src/main/webapp/resources/css/story/storyReview.css
- SeoulGuide/src/main/webapp/resources/css/tour/tour.css
STYLE: tour.jsp/css 반응형으로 수정, 글씨 common.css에 맞춰서 수정
storyreview.jsp, tour.jsp 더보기 버튼 동일하게 수정
> STYLE: tour.jsp/css 수정

- SeoulGuide/src/main/java/com/seoul/guide/like/Controller/likeController.java
- SeoulGuide/src/main/java/com/seoul/guide/like/DAO/likeDAO.java
- SeoulGuide/src/main/java/com/seoul/guide/like/DAO/likeDAOImpl.java
- SeoulGuide/src/main/java/com/seoul/guide/like/DTO/likeDTO.java
- SeoulGuide/src/main/java/com/seoul/guide/like/Service/likeService.java
- SeoulGuide/src/main/java/com/seoul/guide/like/Service/likeServiceImpl.java
- SeoulGuide/src/main/java/com/seoul/guide/tour/Controller/TourController.java
- SeoulGuide/src/main/java/com/seoul/guide/tour/DTO/TourDTO.java
- SeoulGuide/src/main/resources/sql/like.xml
- SeoulGuide/src/main/resources/sql/tour.xml
- SeoulGuide/src/main/webapp/WEB-INF/views/header.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/main.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/member/login.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/tour/tour.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/tour/tourdetail.jsp
- SeoulGuide/src/main/webapp/resources/css/tour/tourdetail.css
- SeoulGuide/src/main/webapp/resources/js/tour.js
FEAT : like.Controller 좋아요 기능 구현 (좋아요, 좋아요 취소)
> FEAT : like.Controller 좋아요 기능 구현 (좋아요, 좋아요 취소)

- SeoulGuide/src/main/webapp/WEB-INF/views/myPage/profile.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/story/storyDetail.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/story/storyModify.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/story/storyReview.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/tour/tour.jsp
- SeoulGuide/src/main/webapp/resources/css/story/storyReview.css
- SeoulGuide/src/main/webapp/resources/css/tour/tour.css
- SeoulGuide/src/main/webapp/resources/js/story.js
- SeoulGuide/src/main/webapp/resources/js/tour.js
STYLE: story.css / tour.css  storyModify.jsp 수정페이지 css완료, tour.css 하드 표시 수정 완료
> STYLE: story.css / tour.css 수정

- SeoulGuide/src/main/java/com/seoul/guide/board/Controller/BoardController.java
- SeoulGuide/src/main/java/com/seoul/guide/board/DTO/Article.java
- SeoulGuide/src/main/java/com/seoul/guide/member/Controller/MypageController.java
- SeoulGuide/src/main/java/com/seoul/guide/member/DAO/MemberDAO.java
- SeoulGuide/src/main/java/com/seoul/guide/member/DAO/MemberDAOImpl.java
- SeoulGuide/src/main/java/com/seoul/guide/member/Service/MemberService.java
- SeoulGuide/src/main/java/com/seoul/guide/member/Service/MemberServiceImpl.java
- SeoulGuide/src/main/resources/sql/board.xml
- SeoulGuide/src/main/resources/sql/member.xml
- SeoulGuide/src/main/webapp/WEB-INF/views/myPage/profile.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/story/storyDetail.jsp
- SeoulGuide/src/main/webapp/WEB-INF/views/story/storyReview.jsp
> FEAT: 마이페이지 나의게시물 업데이트

- SeoulGuide/src/main/webapp/WEB-INF/views/story/storyDetail.jsp
> DOCS: storyDetail.jsp 진행중

- SeoulGuide/src/main/java/com/seoul/guide/member/Controller/MypageController.java
- SeoulGuide/src/main/java/com/seoul/guide/member/DAO/MemberDAO.java
- SeoulGuide/src/main/java/com/seoul/guide/member/DAO/MemberDAOImpl.java
- SeoulGuide/src/main/java/com/seoul/guide/member/Service/MemberService.java
- SeoulGuide/src/main/java/com/seoul/guide/member/Service/MemberServiceImpl.java
- SeoulGuide/src/main/resources/sql/member.xml
- SeoulGuide/src/main/webapp/WEB-INF/views/myPage/profile.jsp
> FEAT: 마이페이지 기능완성 최종!

- SeoulGuide/src/main/java/com/seoul/guide/comment/Controller/CommentController.java
- SeoulGuide/src/main/java/com/seoul/guide/member/Controller/MemberController.java
- SeoulGuide/src/main/java/com/seoul/guide/member/Service/MemberServiceImpl.java
- SeoulGuide/src/main/webapp/resources/css/tour/tour.css
> FIX : 비밀번호 확인 url 수정

- SeoulGuide/src/main/java/com/seoul/guide/member/Controller/MemberController.java
> Fix:passwordfail 부분 오류 수정
